###
POST http://localhost:3001/gimnasio/asistencia/asistenciasdia HTTP/1.1
Content-Type: application/json

{
    "fechaInicio": "2023-09-29",
    "fechaFin": "2023-10-29"
}

###
POST http://localhost:3001/gimnasio/asistencia/asistenciasmes HTTP/1.1
Content-Type: application/json

{
    "fechaInicio": "2023-09-29",
    "fechaFin": "2023-10-29"
}

###
GET http://localhost:3001/gimnasio/rutina/buscar HTTP/1.1

###
POST http://localhost:3001/gimnasio/clientesrutina/login HTTP/1.1
Content-Type: application/json

{
    "celular": "9615487845",
    "contraseña": "s_rqoG7&"
}

###
POST http://localhost:3001/gimnasio/asistencia/buscarasistencia HTTP/1.1
Content-Type: application/json

{
    "id_cliente": 2,
    "fecha": "2023-11-25"
}

###
POST http://localhost:3001/gimnasio/asistencia/registrarplandia HTTP/1.1
Content-Type: application/json

{
    "nombre": "Luis Alberto",
    "apellidoPaterno": "Gutiérrez",
    "apellidoMaterno": "Aguilar",
    "fecha": "2023-09-29"
}

###
POST http://localhost:3001/gimnasio/asistencia/registrarplanmes HTTP/1.1
Content-Type: application/json

{
    "id_cliente": 1,
    "nombre": "Luis Alberto",
    "apellidoPaterno": "Gutiérrez",
    "apellidoMaterno": "Aguilar",
    "fecha": "2023-09-29"
}
###
POST http://localhost:3001/gimnasio/rutina/registrar HTTP/1.1
Content-Type: application/json

{
    "nombre": "Abdomen principiante",
    "descripcion": "1.Crunch Abdominales 2.Twist Ruso 3.Escalada de Montaña 4.Elevaciones de pierna",
    "series": "4",
    "repeticiones": "12" 
}

###
POST http://localhost:3001/gimnasio/clientesrutina/registrar HTTP/1.1
Content-Type: application/json

{
    "nombre": "Luis Alberto",
    "apellidoPaterno": "Gutiérrez",
    "apellidoMaterno": "Aguilar",
    "celular": "9611964939",
    "contraseña": "AAAAAAAA"
}

###
PUT http://localhost:3001/gimnasio/rutina/modificarutina HTTP/1.1
Content-Type: application/json

{
    "nombre": "Brazos",
    "descripcion": "1.Lagartijas 2.Escalada de montaña",
    "series": 4,
    "repeticiones": 8
}

###
DELETE  http://localhost:3001/gimnasio/rutina/eliminarutina HTTP/1.1
Content-Type: application/json

{
    "nombre": "Pecho"
}